[project]
name = "he-gave-me-my-ears"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "markdown>=3.10.2",
    "pelican>=4.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "ty>=0.0.70",
]

[tool.ruff.lint]
extend-select = ["ANN", "Q", "RSE"]
